# Generated by Django 4.0.5 on 2022-07-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualpopulation',
            name='year',
            field=models.IntegerField(),
        ),
    ]
