# Generated by Django 4.0.5 on 2022-07-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_annualpopulation_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualpopulation',
            name='year_country',
            field=models.CharField(default='123', max_length=9, unique=True),
            preserve_default=False,
        ),
    ]
